name: 'company_entity_resolution'
version: '1.0.0'
config-version: 2

profile: 'company_entity_resolution'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  company_entity_resolution:
    materialized: table
    staging:
      materialized: view
    intermediate:
      materialized: table
    marts:
      materialized: table

vars:
  clickhouse_database: "mydb"
  clickhouse_host: "localhost"
  clickhouse_port: 9000
  clickhouse_user: "default"
  clickhouse_password: "" 